apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: shared-resource
spec:
  destination:
    namespace: replace
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd/sync/options/replace/
    repoURL: "https://github.com/foxutech/kubernetes.git"
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
