apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-3
  labels:
    app: webapp-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-3
  template:
    metadata:
      labels:
        app: webapp-3
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
