apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: argocd/sync/options/create-namespace
    repoURL: "https://github.com/foxutech/kubernetes.git"
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        one: two
      annotations:
        abc: xyz
    syncOptions:
    - CreateNamespace=true
