apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do sleep 3600; done
    image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: busybox
