apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-exec-demo
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/testing; sleep 10; rm -rf /tmp/testing; sleep 300
    livenessProbe:
      exec: 
        command:
        - cat
        - /tmp/testing
      initialDelaySeconds: 5
      periodSeconds: 5
