## This file restrictict the project to allow only selected destinaion
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: foxutech
    server: https://kubernetes.default.svc
  project: project-beta
  source:
    path: sample
    repoURL: https://github.com/foxutech/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
