apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
 name: project-delta
 namespace: argocd
spec:
 description: Project delta description
 sourceRepos:
  - "*"
 destinations:
  - server: "*"
    namespace: "*"
 clusterResourceWhitelist:
  - group: "*"
    kind: "*"
 namespaceResourceWhitelist:
  - group: "*"
    kind: "*"  
 roles:
  - name: delta-roles
    description: sync privilefes for delta project
    policies:
    - p, proj:project-delta:delta-roles, applications, sync, project-delta/*, allow
