apiVersion: batch/v1
kind: Job
metadata:
  name: presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "20"]
      restartPolicy: Never
  backoffLimit: 0
